"""
Minimal initial migration reflecting current `stats.models` state.

This migration intentionally mirrors the models currently in
`stats/models.py`: no `refunded` field on `AlbumSale`, no `label_id` fields,
`Rating.stars` allows 0..5 and there is no unique constraint on (user, song_id).

Keep this migration small and consistent with the current DB state so
the project can run without attempting to apply older migration steps
that were applied manually or removed from the models.
"""
from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumSale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("album_id", models.CharField(max_length=64, db_index=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("units", models.PositiveIntegerField(default=1)),
                ("amount", models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ("currency", models.CharField(max_length=3, default="EUR")),
            ],
            options={
                "ordering": ["-purchased_at"],
                "indexes": [models.Index(fields=["album_id", "purchased_at"], name="stats_album_album_i_6ed574_idx")],
            },
        ),
        migrations.CreateModel(
            name="Playback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("song_id", models.CharField(max_length=64, db_index=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("valid", models.BooleanField(default=True)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-played_at"],
                "indexes": [models.Index(fields=["song_id", "played_at"], name="stats_playb_song_id_830617_idx")],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("song_id", models.CharField(max_length=64, db_index=True)),
                ("artist_id", models.CharField(max_length=64, db_index=True, blank=True, null=True)),
                ("stars", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("comment", models.CharField(max_length=512, blank=True)),
                ("rated_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-rated_at"],
                "indexes": [models.Index(fields=["song_id", "artist_id", "rated_at"], name="stats_ratin_song_id_4f6146_idx")],
            },
        ),
    ]
# Generated by Django 5.0.3 on 2025-11-28 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(db_index=True, max_length=64)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('units', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['album_id', 'purchased_at'], name='stats_album_album_i_6ed574_idx')],
            },
        ),
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(db_index=True, max_length=64)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('valid', models.BooleanField(default=True)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['song_id', 'played_at'], name='stats_playb_song_id_830617_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(db_index=True, max_length=64)),
                ('artist_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['song_id', 'artist_id', 'rated_at'], name='stats_ratin_song_id_4f6146_idx')],
            },
        ),
    ]
