# Generated by Copilot assistant - minimal migrations package initializer

__all__ = []
# Minimal migrations package created to satisfy Django's import during runserver.
# The original migrations were backed up to `stats/migrations.bak`.
# This file intentionally contains no migration definitions.
